language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install --upgrade pep8 pyflakes

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -n -w --no-diffs awacs; fi
  - pep8 --version
  - pep8 .
  - pyflakes .

script:
  - python setup.py test
