language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7.3"
  - "3.8"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install --upgrade pycodestyle pyflakes

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -n -w --no-diffs awacs; fi
  - pycodestyle --version
  - pycodestyle --show-source --show-pep8 .
  - pyflakes .

script:
  - python setup.py test
