# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Lambda"
prefix = "lambda"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AddLayerVersionPermission = Action("AddLayerVersionPermission")
AddPermission = Action("AddPermission")
CheckpointDurableExecution = Action("CheckpointDurableExecution")
ConnectMicrovm = Action("ConnectMicrovm")
CreateAlias = Action("CreateAlias")
CreateCapacityProvider = Action("CreateCapacityProvider")
CreateCodeSigningConfig = Action("CreateCodeSigningConfig")
CreateEventSourceMapping = Action("CreateEventSourceMapping")
CreateFunction = Action("CreateFunction")
CreateFunctionUrlConfig = Action("CreateFunctionUrlConfig")
CreateMicrovmAuthToken = Action("CreateMicrovmAuthToken")
CreateMicrovmImage = Action("CreateMicrovmImage")
CreateMicrovmShellAuthToken = Action("CreateMicrovmShellAuthToken")
CreateNetworkConnector = Action("CreateNetworkConnector")
DeleteAlias = Action("DeleteAlias")
DeleteCapacityProvider = Action("DeleteCapacityProvider")
DeleteCodeSigningConfig = Action("DeleteCodeSigningConfig")
DeleteEventSourceMapping = Action("DeleteEventSourceMapping")
DeleteFunction = Action("DeleteFunction")
DeleteFunctionCodeSigningConfig = Action("DeleteFunctionCodeSigningConfig")
DeleteFunctionConcurrency = Action("DeleteFunctionConcurrency")
DeleteFunctionEventInvokeConfig = Action("DeleteFunctionEventInvokeConfig")
DeleteFunctionUrlConfig = Action("DeleteFunctionUrlConfig")
DeleteLayerVersion = Action("DeleteLayerVersion")
DeleteMicrovmImage = Action("DeleteMicrovmImage")
DeleteMicrovmImageVersion = Action("DeleteMicrovmImageVersion")
DeleteNetworkConnector = Action("DeleteNetworkConnector")
DeleteProvisionedConcurrencyConfig = Action("DeleteProvisionedConcurrencyConfig")
DeleteResourcePolicy = Action("DeleteResourcePolicy")
DisableReplication = Action("DisableReplication")
EnableReplication = Action("EnableReplication")
GetAccountSettings = Action("GetAccountSettings")
GetAlias = Action("GetAlias")
GetCapacityProvider = Action("GetCapacityProvider")
GetCodeSigningConfig = Action("GetCodeSigningConfig")
GetDurableExecution = Action("GetDurableExecution")
GetDurableExecutionHistory = Action("GetDurableExecutionHistory")
GetDurableExecutionState = Action("GetDurableExecutionState")
GetEventSourceMapping = Action("GetEventSourceMapping")
GetFunction = Action("GetFunction")
GetFunctionCodeSigningConfig = Action("GetFunctionCodeSigningConfig")
GetFunctionConcurrency = Action("GetFunctionConcurrency")
GetFunctionConfiguration = Action("GetFunctionConfiguration")
GetFunctionEventInvokeConfig = Action("GetFunctionEventInvokeConfig")
GetFunctionRecursionConfig = Action("GetFunctionRecursionConfig")
GetFunctionScalingConfig = Action("GetFunctionScalingConfig")
GetFunctionUrlConfig = Action("GetFunctionUrlConfig")
GetLayerVersion = Action("GetLayerVersion")
GetLayerVersionByArn = Action("GetLayerVersionByArn")
GetLayerVersionPolicy = Action("GetLayerVersionPolicy")
GetMicrovm = Action("GetMicrovm")
GetMicrovmImage = Action("GetMicrovmImage")
GetMicrovmImageBuild = Action("GetMicrovmImageBuild")
GetMicrovmImageVersion = Action("GetMicrovmImageVersion")
GetNetworkConnector = Action("GetNetworkConnector")
GetPolicy = Action("GetPolicy")
GetProvisionedConcurrencyConfig = Action("GetProvisionedConcurrencyConfig")
GetResourcePolicy = Action("GetResourcePolicy")
GetRuntimeManagementConfig = Action("GetRuntimeManagementConfig")
InvokeAsync = Action("InvokeAsync")
InvokeFunction = Action("InvokeFunction")
InvokeFunctionUrl = Action("InvokeFunctionUrl")
ListAliases = Action("ListAliases")
ListCapacityProviders = Action("ListCapacityProviders")
ListCodeSigningConfigs = Action("ListCodeSigningConfigs")
ListDurableExecutionsByFunction = Action("ListDurableExecutionsByFunction")
ListEventSourceMappings = Action("ListEventSourceMappings")
ListFunctionEventInvokeConfigs = Action("ListFunctionEventInvokeConfigs")
ListFunctionUrlConfigs = Action("ListFunctionUrlConfigs")
ListFunctionVersionsByCapacityProvider = Action(
    "ListFunctionVersionsByCapacityProvider"
)
ListFunctions = Action("ListFunctions")
ListFunctionsByCodeSigningConfig = Action("ListFunctionsByCodeSigningConfig")
ListLayerVersions = Action("ListLayerVersions")
ListLayers = Action("ListLayers")
ListManagedMicrovmImageVersions = Action("ListManagedMicrovmImageVersions")
ListManagedMicrovmImages = Action("ListManagedMicrovmImages")
ListMicrovmImageBuilds = Action("ListMicrovmImageBuilds")
ListMicrovmImageVersions = Action("ListMicrovmImageVersions")
ListMicrovmImages = Action("ListMicrovmImages")
ListMicrovms = Action("ListMicrovms")
ListNetworkConnectors = Action("ListNetworkConnectors")
ListProvisionedConcurrencyConfigs = Action("ListProvisionedConcurrencyConfigs")
ListTags = Action("ListTags")
ListVersionsByFunction = Action("ListVersionsByFunction")
PassCapacityProvider = Action("PassCapacityProvider")
PassNetworkConnector = Action("PassNetworkConnector")
PublishLayerVersion = Action("PublishLayerVersion")
PublishVersion = Action("PublishVersion")
PutFunctionCodeSigningConfig = Action("PutFunctionCodeSigningConfig")
PutFunctionConcurrency = Action("PutFunctionConcurrency")
PutFunctionEventInvokeConfig = Action("PutFunctionEventInvokeConfig")
PutFunctionRecursionConfig = Action("PutFunctionRecursionConfig")
PutFunctionScalingConfig = Action("PutFunctionScalingConfig")
PutProvisionedConcurrencyConfig = Action("PutProvisionedConcurrencyConfig")
PutResourcePolicy = Action("PutResourcePolicy")
PutRuntimeManagementConfig = Action("PutRuntimeManagementConfig")
RemoveLayerVersionPermission = Action("RemoveLayerVersionPermission")
RemovePermission = Action("RemovePermission")
ResumeMicrovm = Action("ResumeMicrovm")
RunMicrovm = Action("RunMicrovm")
SendDurableExecutionCallbackFailure = Action("SendDurableExecutionCallbackFailure")
SendDurableExecutionCallbackHeartbeat = Action("SendDurableExecutionCallbackHeartbeat")
SendDurableExecutionCallbackSuccess = Action("SendDurableExecutionCallbackSuccess")
StopDurableExecution = Action("StopDurableExecution")
SuspendMicrovm = Action("SuspendMicrovm")
TagResource = Action("TagResource")
TerminateMicrovm = Action("TerminateMicrovm")
UntagResource = Action("UntagResource")
UpdateAlias = Action("UpdateAlias")
UpdateCapacityProvider = Action("UpdateCapacityProvider")
UpdateCodeSigningConfig = Action("UpdateCodeSigningConfig")
UpdateEventSourceMapping = Action("UpdateEventSourceMapping")
UpdateFunctionCode = Action("UpdateFunctionCode")
UpdateFunctionCodeSigningConfig = Action("UpdateFunctionCodeSigningConfig")
UpdateFunctionConfiguration = Action("UpdateFunctionConfiguration")
UpdateFunctionEventInvokeConfig = Action("UpdateFunctionEventInvokeConfig")
UpdateFunctionUrlConfig = Action("UpdateFunctionUrlConfig")
UpdateMicrovmImage = Action("UpdateMicrovmImage")
UpdateMicrovmImageVersion = Action("UpdateMicrovmImageVersion")
UpdateNetworkConnector = Action("UpdateNetworkConnector")
