# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Bedrock Agentcore"
prefix = "bedrock-agentcore"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AllowVendedLogDeliveryForResource = Action("AllowVendedLogDeliveryForResource")
AuthorizeAction = Action("AuthorizeAction")
BatchCreateMemoryRecords = Action("BatchCreateMemoryRecords")
BatchDeleteMemoryRecords = Action("BatchDeleteMemoryRecords")
BatchUpdateMemoryRecords = Action("BatchUpdateMemoryRecords")
CompleteResourceTokenAuth = Action("CompleteResourceTokenAuth")
ConnectBrowserAutomationStream = Action("ConnectBrowserAutomationStream")
ConnectBrowserLiveViewStream = Action("ConnectBrowserLiveViewStream")
CreateABTest = Action("CreateABTest")
CreateAgentRuntime = Action("CreateAgentRuntime")
CreateAgentRuntimeEndpoint = Action("CreateAgentRuntimeEndpoint")
CreateApiKeyCredentialProvider = Action("CreateApiKeyCredentialProvider")
CreateBrowser = Action("CreateBrowser")
CreateBrowserProfile = Action("CreateBrowserProfile")
CreateCodeInterpreter = Action("CreateCodeInterpreter")
CreateConfigurationBundle = Action("CreateConfigurationBundle")
CreateEvaluator = Action("CreateEvaluator")
CreateEvent = Action("CreateEvent")
CreateGateway = Action("CreateGateway")
CreateGatewayRule = Action("CreateGatewayRule")
CreateGatewayTarget = Action("CreateGatewayTarget")
CreateHarness = Action("CreateHarness")
CreateMemory = Action("CreateMemory")
CreateOauth2CredentialProvider = Action("CreateOauth2CredentialProvider")
CreateOnlineEvaluationConfig = Action("CreateOnlineEvaluationConfig")
CreatePaymentConnector = Action("CreatePaymentConnector")
CreatePaymentCredentialProvider = Action("CreatePaymentCredentialProvider")
CreatePaymentInstrument = Action("CreatePaymentInstrument")
CreatePaymentManager = Action("CreatePaymentManager")
CreatePaymentSession = Action("CreatePaymentSession")
CreatePolicy = Action("CreatePolicy")
CreatePolicyEngine = Action("CreatePolicyEngine")
CreateRegistry = Action("CreateRegistry")
CreateRegistryRecord = Action("CreateRegistryRecord")
CreateWorkloadIdentity = Action("CreateWorkloadIdentity")
DeleteABTest = Action("DeleteABTest")
DeleteAgentRuntime = Action("DeleteAgentRuntime")
DeleteAgentRuntimeEndpoint = Action("DeleteAgentRuntimeEndpoint")
DeleteApiKeyCredentialProvider = Action("DeleteApiKeyCredentialProvider")
DeleteBatchEvaluation = Action("DeleteBatchEvaluation")
DeleteBrowser = Action("DeleteBrowser")
DeleteBrowserProfile = Action("DeleteBrowserProfile")
DeleteCodeInterpreter = Action("DeleteCodeInterpreter")
DeleteConfigurationBundle = Action("DeleteConfigurationBundle")
DeleteEvaluator = Action("DeleteEvaluator")
DeleteEvent = Action("DeleteEvent")
DeleteGateway = Action("DeleteGateway")
DeleteGatewayRule = Action("DeleteGatewayRule")
DeleteGatewayTarget = Action("DeleteGatewayTarget")
DeleteHarness = Action("DeleteHarness")
DeleteMemory = Action("DeleteMemory")
DeleteMemoryRecord = Action("DeleteMemoryRecord")
DeleteOauth2CredentialProvider = Action("DeleteOauth2CredentialProvider")
DeleteOnlineEvaluationConfig = Action("DeleteOnlineEvaluationConfig")
DeletePaymentConnector = Action("DeletePaymentConnector")
DeletePaymentCredentialProvider = Action("DeletePaymentCredentialProvider")
DeletePaymentInstrument = Action("DeletePaymentInstrument")
DeletePaymentManager = Action("DeletePaymentManager")
DeletePaymentSession = Action("DeletePaymentSession")
DeletePolicy = Action("DeletePolicy")
DeletePolicyEngine = Action("DeletePolicyEngine")
DeleteRecommendation = Action("DeleteRecommendation")
DeleteRegistry = Action("DeleteRegistry")
DeleteRegistryRecord = Action("DeleteRegistryRecord")
DeleteResourcePolicy = Action("DeleteResourcePolicy")
DeleteWorkloadIdentity = Action("DeleteWorkloadIdentity")
Evaluate = Action("Evaluate")
GetABTest = Action("GetABTest")
GetAgentCard = Action("GetAgentCard")
GetAgentRuntime = Action("GetAgentRuntime")
GetAgentRuntimeEndpoint = Action("GetAgentRuntimeEndpoint")
GetApiKeyCredentialProvider = Action("GetApiKeyCredentialProvider")
GetBatchEvaluation = Action("GetBatchEvaluation")
GetBrowser = Action("GetBrowser")
GetBrowserProfile = Action("GetBrowserProfile")
GetBrowserSession = Action("GetBrowserSession")
GetCodeInterpreter = Action("GetCodeInterpreter")
GetCodeInterpreterSession = Action("GetCodeInterpreterSession")
GetConfigurationBundle = Action("GetConfigurationBundle")
GetConfigurationBundleVersion = Action("GetConfigurationBundleVersion")
GetEvaluator = Action("GetEvaluator")
GetEvent = Action("GetEvent")
GetGateway = Action("GetGateway")
GetGatewayRule = Action("GetGatewayRule")
GetGatewayTarget = Action("GetGatewayTarget")
GetHarness = Action("GetHarness")
GetMemory = Action("GetMemory")
GetMemoryRecord = Action("GetMemoryRecord")
GetOauth2CredentialProvider = Action("GetOauth2CredentialProvider")
GetOnlineEvaluationConfig = Action("GetOnlineEvaluationConfig")
GetPaymentConnector = Action("GetPaymentConnector")
GetPaymentCredentialProvider = Action("GetPaymentCredentialProvider")
GetPaymentInstrument = Action("GetPaymentInstrument")
GetPaymentInstrumentBalance = Action("GetPaymentInstrumentBalance")
GetPaymentManager = Action("GetPaymentManager")
GetPaymentSession = Action("GetPaymentSession")
GetPolicy = Action("GetPolicy")
GetPolicyEngine = Action("GetPolicyEngine")
GetPolicyGeneration = Action("GetPolicyGeneration")
GetRecommendation = Action("GetRecommendation")
GetRegistry = Action("GetRegistry")
GetRegistryRecord = Action("GetRegistryRecord")
GetResourceApiKey = Action("GetResourceApiKey")
GetResourceOauth2Token = Action("GetResourceOauth2Token")
GetResourcePaymentToken = Action("GetResourcePaymentToken")
GetResourcePolicy = Action("GetResourcePolicy")
GetTokenVault = Action("GetTokenVault")
GetWorkloadAccessToken = Action("GetWorkloadAccessToken")
GetWorkloadAccessTokenForJWT = Action("GetWorkloadAccessTokenForJWT")
GetWorkloadAccessTokenForUserId = Action("GetWorkloadAccessTokenForUserId")
GetWorkloadIdentity = Action("GetWorkloadIdentity")
InvokeAgentRuntime = Action("InvokeAgentRuntime")
InvokeAgentRuntimeCommand = Action("InvokeAgentRuntimeCommand")
InvokeAgentRuntimeEndpoint = Action("InvokeAgentRuntimeEndpoint")
InvokeAgentRuntimeForUser = Action("InvokeAgentRuntimeForUser")
InvokeAgentRuntimeWithWebSocketStream = Action("InvokeAgentRuntimeWithWebSocketStream")
InvokeAgentRuntimeWithWebSocketStreamForUser = Action(
    "InvokeAgentRuntimeWithWebSocketStreamForUser"
)
InvokeCodeInterpreter = Action("InvokeCodeInterpreter")
InvokeGateway = Action("InvokeGateway")
InvokeHarness = Action("InvokeHarness")
InvokeRegistryMcp = Action("InvokeRegistryMcp")
ListABTests = Action("ListABTests")
ListActors = Action("ListActors")
ListAgentRuntimeEndpoints = Action("ListAgentRuntimeEndpoints")
ListAgentRuntimeVersions = Action("ListAgentRuntimeVersions")
ListAgentRuntimes = Action("ListAgentRuntimes")
ListApiKeyCredentialProviders = Action("ListApiKeyCredentialProviders")
ListBatchEvaluations = Action("ListBatchEvaluations")
ListBrowserProfiles = Action("ListBrowserProfiles")
ListBrowserSessions = Action("ListBrowserSessions")
ListBrowsers = Action("ListBrowsers")
ListCodeInterpreterSessions = Action("ListCodeInterpreterSessions")
ListCodeInterpreters = Action("ListCodeInterpreters")
ListConfigurationBundleVersions = Action("ListConfigurationBundleVersions")
ListConfigurationBundles = Action("ListConfigurationBundles")
ListEvaluators = Action("ListEvaluators")
ListEvents = Action("ListEvents")
ListGatewayRules = Action("ListGatewayRules")
ListGatewayTargets = Action("ListGatewayTargets")
ListGateways = Action("ListGateways")
ListHarnesses = Action("ListHarnesses")
ListMemories = Action("ListMemories")
ListMemoryExtractionJobs = Action("ListMemoryExtractionJobs")
ListMemoryRecords = Action("ListMemoryRecords")
ListOauth2CredentialProviders = Action("ListOauth2CredentialProviders")
ListOnlineEvaluationConfigs = Action("ListOnlineEvaluationConfigs")
ListPaymentConnectors = Action("ListPaymentConnectors")
ListPaymentCredentialProviders = Action("ListPaymentCredentialProviders")
ListPaymentInstruments = Action("ListPaymentInstruments")
ListPaymentManagers = Action("ListPaymentManagers")
ListPaymentSessions = Action("ListPaymentSessions")
ListPolicies = Action("ListPolicies")
ListPolicyEngines = Action("ListPolicyEngines")
ListPolicyGenerationAssets = Action("ListPolicyGenerationAssets")
ListPolicyGenerations = Action("ListPolicyGenerations")
ListRecommendations = Action("ListRecommendations")
ListRegistries = Action("ListRegistries")
ListRegistryRecords = Action("ListRegistryRecords")
ListSessions = Action("ListSessions")
ListTagsForResource = Action("ListTagsForResource")
ListWorkloadIdentities = Action("ListWorkloadIdentities")
ManageAdminPolicy = Action("ManageAdminPolicy")
ManageResourceScopedPolicy = Action("ManageResourceScopedPolicy")
PartiallyAuthorizeActions = Action("PartiallyAuthorizeActions")
ProcessPayment = Action("ProcessPayment")
PutResourcePolicy = Action("PutResourcePolicy")
RetrieveMemoryRecords = Action("RetrieveMemoryRecords")
SaveBrowserSessionProfile = Action("SaveBrowserSessionProfile")
SearchRegistryRecords = Action("SearchRegistryRecords")
SetTokenVaultCMK = Action("SetTokenVaultCMK")
StartBatchEvaluation = Action("StartBatchEvaluation")
StartBrowserSession = Action("StartBrowserSession")
StartCodeInterpreterSession = Action("StartCodeInterpreterSession")
StartMemoryExtractionJob = Action("StartMemoryExtractionJob")
StartPolicyGeneration = Action("StartPolicyGeneration")
StartRecommendation = Action("StartRecommendation")
StopBatchEvaluation = Action("StopBatchEvaluation")
StopBrowserSession = Action("StopBrowserSession")
StopCodeInterpreterSession = Action("StopCodeInterpreterSession")
StopRuntimeSession = Action("StopRuntimeSession")
SubmitRegistryRecordForApproval = Action("SubmitRegistryRecordForApproval")
SynchronizeGatewayTargets = Action("SynchronizeGatewayTargets")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateABTest = Action("UpdateABTest")
UpdateAgentRuntime = Action("UpdateAgentRuntime")
UpdateAgentRuntimeEndpoint = Action("UpdateAgentRuntimeEndpoint")
UpdateApiKeyCredentialProvider = Action("UpdateApiKeyCredentialProvider")
UpdateBrowserStream = Action("UpdateBrowserStream")
UpdateConfigurationBundle = Action("UpdateConfigurationBundle")
UpdateEvaluator = Action("UpdateEvaluator")
UpdateGateway = Action("UpdateGateway")
UpdateGatewayRule = Action("UpdateGatewayRule")
UpdateGatewayTarget = Action("UpdateGatewayTarget")
UpdateHarness = Action("UpdateHarness")
UpdateMemory = Action("UpdateMemory")
UpdateOauth2CredentialProvider = Action("UpdateOauth2CredentialProvider")
UpdateOnlineEvaluationConfig = Action("UpdateOnlineEvaluationConfig")
UpdatePaymentConnector = Action("UpdatePaymentConnector")
UpdatePaymentCredentialProvider = Action("UpdatePaymentCredentialProvider")
UpdatePaymentManager = Action("UpdatePaymentManager")
UpdatePolicy = Action("UpdatePolicy")
UpdatePolicyEngine = Action("UpdatePolicyEngine")
UpdateRegistry = Action("UpdateRegistry")
UpdateRegistryRecord = Action("UpdateRegistryRecord")
UpdateRegistryRecordStatus = Action("UpdateRegistryRecordStatus")
UpdateWorkloadIdentity = Action("UpdateWorkloadIdentity")
