# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Bedrock Agentcore"
prefix = "bedrock-agentcore"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AllowVendedLogDeliveryForResource = Action("AllowVendedLogDeliveryForResource")
AuthorizeAction = Action("AuthorizeAction")
BatchCreateMemoryRecords = Action("BatchCreateMemoryRecords")
BatchDeleteMemoryRecords = Action("BatchDeleteMemoryRecords")
BatchUpdateMemoryRecords = Action("BatchUpdateMemoryRecords")
CompleteResourceTokenAuth = Action("CompleteResourceTokenAuth")
ConnectBrowserAutomationStream = Action("ConnectBrowserAutomationStream")
ConnectBrowserLiveViewStream = Action("ConnectBrowserLiveViewStream")
CreateAgentRuntime = Action("CreateAgentRuntime")
CreateAgentRuntimeEndpoint = Action("CreateAgentRuntimeEndpoint")
CreateApiKeyCredentialProvider = Action("CreateApiKeyCredentialProvider")
CreateBrowser = Action("CreateBrowser")
CreateBrowserProfile = Action("CreateBrowserProfile")
CreateCodeInterpreter = Action("CreateCodeInterpreter")
CreateEvaluator = Action("CreateEvaluator")
CreateEvent = Action("CreateEvent")
CreateGateway = Action("CreateGateway")
CreateGatewayTarget = Action("CreateGatewayTarget")
CreateMemory = Action("CreateMemory")
CreateOauth2CredentialProvider = Action("CreateOauth2CredentialProvider")
CreateOnlineEvaluationConfig = Action("CreateOnlineEvaluationConfig")
CreatePolicy = Action("CreatePolicy")
CreatePolicyEngine = Action("CreatePolicyEngine")
CreateWorkloadIdentity = Action("CreateWorkloadIdentity")
DeleteAgentRuntime = Action("DeleteAgentRuntime")
DeleteAgentRuntimeEndpoint = Action("DeleteAgentRuntimeEndpoint")
DeleteApiKeyCredentialProvider = Action("DeleteApiKeyCredentialProvider")
DeleteBrowser = Action("DeleteBrowser")
DeleteBrowserProfile = Action("DeleteBrowserProfile")
DeleteCodeInterpreter = Action("DeleteCodeInterpreter")
DeleteEvaluator = Action("DeleteEvaluator")
DeleteEvent = Action("DeleteEvent")
DeleteGateway = Action("DeleteGateway")
DeleteGatewayTarget = Action("DeleteGatewayTarget")
DeleteMemory = Action("DeleteMemory")
DeleteMemoryRecord = Action("DeleteMemoryRecord")
DeleteOauth2CredentialProvider = Action("DeleteOauth2CredentialProvider")
DeleteOnlineEvaluationConfig = Action("DeleteOnlineEvaluationConfig")
DeletePolicy = Action("DeletePolicy")
DeletePolicyEngine = Action("DeletePolicyEngine")
DeleteResourcePolicy = Action("DeleteResourcePolicy")
DeleteWorkloadIdentity = Action("DeleteWorkloadIdentity")
Evaluate = Action("Evaluate")
GetAgentCard = Action("GetAgentCard")
GetAgentRuntime = Action("GetAgentRuntime")
GetAgentRuntimeEndpoint = Action("GetAgentRuntimeEndpoint")
GetApiKeyCredentialProvider = Action("GetApiKeyCredentialProvider")
GetBrowser = Action("GetBrowser")
GetBrowserProfile = Action("GetBrowserProfile")
GetBrowserSession = Action("GetBrowserSession")
GetCodeInterpreter = Action("GetCodeInterpreter")
GetCodeInterpreterSession = Action("GetCodeInterpreterSession")
GetEvaluator = Action("GetEvaluator")
GetEvent = Action("GetEvent")
GetGateway = Action("GetGateway")
GetGatewayTarget = Action("GetGatewayTarget")
GetMemory = Action("GetMemory")
GetMemoryRecord = Action("GetMemoryRecord")
GetOauth2CredentialProvider = Action("GetOauth2CredentialProvider")
GetOnlineEvaluationConfig = Action("GetOnlineEvaluationConfig")
GetPolicy = Action("GetPolicy")
GetPolicyEngine = Action("GetPolicyEngine")
GetPolicyGeneration = Action("GetPolicyGeneration")
GetResourceApiKey = Action("GetResourceApiKey")
GetResourceOauth2Token = Action("GetResourceOauth2Token")
GetResourcePolicy = Action("GetResourcePolicy")
GetTokenVault = Action("GetTokenVault")
GetWorkloadAccessToken = Action("GetWorkloadAccessToken")
GetWorkloadAccessTokenForJWT = Action("GetWorkloadAccessTokenForJWT")
GetWorkloadAccessTokenForUserId = Action("GetWorkloadAccessTokenForUserId")
GetWorkloadIdentity = Action("GetWorkloadIdentity")
InvokeAgentRuntime = Action("InvokeAgentRuntime")
InvokeAgentRuntimeEndpoint = Action("InvokeAgentRuntimeEndpoint")
InvokeAgentRuntimeForUser = Action("InvokeAgentRuntimeForUser")
InvokeAgentRuntimeWithWebSocketStream = Action("InvokeAgentRuntimeWithWebSocketStream")
InvokeAgentRuntimeWithWebSocketStreamForUser = Action(
    "InvokeAgentRuntimeWithWebSocketStreamForUser"
)
InvokeCodeInterpreter = Action("InvokeCodeInterpreter")
InvokeGateway = Action("InvokeGateway")
ListActors = Action("ListActors")
ListAgentRuntimeEndpoints = Action("ListAgentRuntimeEndpoints")
ListAgentRuntimeVersions = Action("ListAgentRuntimeVersions")
ListAgentRuntimes = Action("ListAgentRuntimes")
ListApiKeyCredentialProviders = Action("ListApiKeyCredentialProviders")
ListBrowserProfiles = Action("ListBrowserProfiles")
ListBrowserSessions = Action("ListBrowserSessions")
ListBrowsers = Action("ListBrowsers")
ListCodeInterpreterSessions = Action("ListCodeInterpreterSessions")
ListCodeInterpreters = Action("ListCodeInterpreters")
ListEvaluators = Action("ListEvaluators")
ListEvents = Action("ListEvents")
ListGatewayTargets = Action("ListGatewayTargets")
ListGateways = Action("ListGateways")
ListMemories = Action("ListMemories")
ListMemoryExtractionJobs = Action("ListMemoryExtractionJobs")
ListMemoryRecords = Action("ListMemoryRecords")
ListOauth2CredentialProviders = Action("ListOauth2CredentialProviders")
ListOnlineEvaluationConfigs = Action("ListOnlineEvaluationConfigs")
ListPolicies = Action("ListPolicies")
ListPolicyEngines = Action("ListPolicyEngines")
ListPolicyGenerationAssets = Action("ListPolicyGenerationAssets")
ListPolicyGenerations = Action("ListPolicyGenerations")
ListSessions = Action("ListSessions")
ListTagsForResource = Action("ListTagsForResource")
ListWorkloadIdentities = Action("ListWorkloadIdentities")
ManageAdminPolicy = Action("ManageAdminPolicy")
ManageResourceScopedPolicy = Action("ManageResourceScopedPolicy")
PartiallyAuthorizeActions = Action("PartiallyAuthorizeActions")
PutResourcePolicy = Action("PutResourcePolicy")
RetrieveMemoryRecords = Action("RetrieveMemoryRecords")
SaveBrowserSessionProfile = Action("SaveBrowserSessionProfile")
SetTokenVaultCMK = Action("SetTokenVaultCMK")
StartBrowserSession = Action("StartBrowserSession")
StartCodeInterpreterSession = Action("StartCodeInterpreterSession")
StartMemoryExtractionJob = Action("StartMemoryExtractionJob")
StartPolicyGeneration = Action("StartPolicyGeneration")
StopBrowserSession = Action("StopBrowserSession")
StopCodeInterpreterSession = Action("StopCodeInterpreterSession")
StopRuntimeSession = Action("StopRuntimeSession")
SynchronizeGatewayTargets = Action("SynchronizeGatewayTargets")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateAgentRuntime = Action("UpdateAgentRuntime")
UpdateAgentRuntimeEndpoint = Action("UpdateAgentRuntimeEndpoint")
UpdateApiKeyCredentialProvider = Action("UpdateApiKeyCredentialProvider")
UpdateBrowserStream = Action("UpdateBrowserStream")
UpdateEvaluator = Action("UpdateEvaluator")
UpdateGateway = Action("UpdateGateway")
UpdateGatewayTarget = Action("UpdateGatewayTarget")
UpdateMemory = Action("UpdateMemory")
UpdateOauth2CredentialProvider = Action("UpdateOauth2CredentialProvider")
UpdateOnlineEvaluationConfig = Action("UpdateOnlineEvaluationConfig")
UpdatePolicy = Action("UpdatePolicy")
UpdatePolicyEngine = Action("UpdatePolicyEngine")
UpdateWorkloadIdentity = Action("UpdateWorkloadIdentity")
