# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon CloudFront"
prefix = "cloudfront"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AllowVendedLogDeliveryForResource = Action("AllowVendedLogDeliveryForResource")
AssociateAlias = Action("AssociateAlias")
AssociateDistributionTenantWebACL = Action("AssociateDistributionTenantWebACL")
AssociateDistributionWebACL = Action("AssociateDistributionWebACL")
CopyDistribution = Action("CopyDistribution")
CreateAnycastIpList = Action("CreateAnycastIpList")
CreateCachePolicy = Action("CreateCachePolicy")
CreateCloudFrontOriginAccessIdentity = Action("CreateCloudFrontOriginAccessIdentity")
CreateConnectionFunction = Action("CreateConnectionFunction")
CreateConnectionGroup = Action("CreateConnectionGroup")
CreateContinuousDeploymentPolicy = Action("CreateContinuousDeploymentPolicy")
CreateDistribution = Action("CreateDistribution")
CreateDistributionTenant = Action("CreateDistributionTenant")
CreateDistributionWithTags = Action("CreateDistributionWithTags")
CreateFieldLevelEncryptionConfig = Action("CreateFieldLevelEncryptionConfig")
CreateFieldLevelEncryptionProfile = Action("CreateFieldLevelEncryptionProfile")
CreateFunction = Action("CreateFunction")
CreateInvalidation = Action("CreateInvalidation")
CreateInvalidationForDistributionTenant = Action(
    "CreateInvalidationForDistributionTenant"
)
CreateKeyGroup = Action("CreateKeyGroup")
CreateKeyValueStore = Action("CreateKeyValueStore")
CreateMonitoringSubscription = Action("CreateMonitoringSubscription")
CreateOriginAccessControl = Action("CreateOriginAccessControl")
CreateOriginRequestPolicy = Action("CreateOriginRequestPolicy")
CreatePublicKey = Action("CreatePublicKey")
CreateRealtimeLogConfig = Action("CreateRealtimeLogConfig")
CreateResponseHeadersPolicy = Action("CreateResponseHeadersPolicy")
CreateSavingsPlan = Action("CreateSavingsPlan")
CreateStreamingDistribution = Action("CreateStreamingDistribution")
CreateStreamingDistributionWithTags = Action("CreateStreamingDistributionWithTags")
CreateTrustStore = Action("CreateTrustStore")
CreateVpcOrigin = Action("CreateVpcOrigin")
DeleteAnycastIpList = Action("DeleteAnycastIpList")
DeleteCachePolicy = Action("DeleteCachePolicy")
DeleteCloudFrontOriginAccessIdentity = Action("DeleteCloudFrontOriginAccessIdentity")
DeleteConnectionFunction = Action("DeleteConnectionFunction")
DeleteConnectionGroup = Action("DeleteConnectionGroup")
DeleteContinuousDeploymentPolicy = Action("DeleteContinuousDeploymentPolicy")
DeleteDistribution = Action("DeleteDistribution")
DeleteDistributionTenant = Action("DeleteDistributionTenant")
DeleteFieldLevelEncryptionConfig = Action("DeleteFieldLevelEncryptionConfig")
DeleteFieldLevelEncryptionProfile = Action("DeleteFieldLevelEncryptionProfile")
DeleteFunction = Action("DeleteFunction")
DeleteKeyGroup = Action("DeleteKeyGroup")
DeleteKeyValueStore = Action("DeleteKeyValueStore")
DeleteMonitoringSubscription = Action("DeleteMonitoringSubscription")
DeleteOriginAccessControl = Action("DeleteOriginAccessControl")
DeleteOriginRequestPolicy = Action("DeleteOriginRequestPolicy")
DeletePublicKey = Action("DeletePublicKey")
DeleteRealtimeLogConfig = Action("DeleteRealtimeLogConfig")
DeleteResourcePolicy = Action("DeleteResourcePolicy")
DeleteResponseHeadersPolicy = Action("DeleteResponseHeadersPolicy")
DeleteStreamingDistribution = Action("DeleteStreamingDistribution")
DeleteTrustStore = Action("DeleteTrustStore")
DeleteVpcOrigin = Action("DeleteVpcOrigin")
DescribeConnectionFunction = Action("DescribeConnectionFunction")
DescribeFunction = Action("DescribeFunction")
DescribeKeyValueStore = Action("DescribeKeyValueStore")
DisassociateDistributionTenantWebACL = Action("DisassociateDistributionTenantWebACL")
DisassociateDistributionWebACL = Action("DisassociateDistributionWebACL")
GetAnycastIpList = Action("GetAnycastIpList")
GetCachePolicy = Action("GetCachePolicy")
GetCachePolicyConfig = Action("GetCachePolicyConfig")
GetCloudFrontOriginAccessIdentity = Action("GetCloudFrontOriginAccessIdentity")
GetCloudFrontOriginAccessIdentityConfig = Action(
    "GetCloudFrontOriginAccessIdentityConfig"
)
GetConnectionFunction = Action("GetConnectionFunction")
GetConnectionGroup = Action("GetConnectionGroup")
GetConnectionGroupByRoutingEndpoint = Action("GetConnectionGroupByRoutingEndpoint")
GetContinuousDeploymentPolicy = Action("GetContinuousDeploymentPolicy")
GetContinuousDeploymentPolicyConfig = Action("GetContinuousDeploymentPolicyConfig")
GetDistribution = Action("GetDistribution")
GetDistributionConfig = Action("GetDistributionConfig")
GetDistributionTenant = Action("GetDistributionTenant")
GetDistributionTenantByDomain = Action("GetDistributionTenantByDomain")
GetFieldLevelEncryption = Action("GetFieldLevelEncryption")
GetFieldLevelEncryptionConfig = Action("GetFieldLevelEncryptionConfig")
GetFieldLevelEncryptionProfile = Action("GetFieldLevelEncryptionProfile")
GetFieldLevelEncryptionProfileConfig = Action("GetFieldLevelEncryptionProfileConfig")
GetFunction = Action("GetFunction")
GetInvalidation = Action("GetInvalidation")
GetInvalidationForDistributionTenant = Action("GetInvalidationForDistributionTenant")
GetKeyGroup = Action("GetKeyGroup")
GetKeyGroupConfig = Action("GetKeyGroupConfig")
GetManagedCertificateDetails = Action("GetManagedCertificateDetails")
GetMonitoringSubscription = Action("GetMonitoringSubscription")
GetOriginAccessControl = Action("GetOriginAccessControl")
GetOriginAccessControlConfig = Action("GetOriginAccessControlConfig")
GetOriginRequestPolicy = Action("GetOriginRequestPolicy")
GetOriginRequestPolicyConfig = Action("GetOriginRequestPolicyConfig")
GetPublicKey = Action("GetPublicKey")
GetPublicKeyConfig = Action("GetPublicKeyConfig")
GetRealtimeLogConfig = Action("GetRealtimeLogConfig")
GetResourcePolicy = Action("GetResourcePolicy")
GetResponseHeadersPolicy = Action("GetResponseHeadersPolicy")
GetResponseHeadersPolicyConfig = Action("GetResponseHeadersPolicyConfig")
GetSavingsPlan = Action("GetSavingsPlan")
GetStreamingDistribution = Action("GetStreamingDistribution")
GetStreamingDistributionConfig = Action("GetStreamingDistributionConfig")
GetTrustStore = Action("GetTrustStore")
GetVpcOrigin = Action("GetVpcOrigin")
ListAnycastIpLists = Action("ListAnycastIpLists")
ListCachePolicies = Action("ListCachePolicies")
ListCloudFrontOriginAccessIdentities = Action("ListCloudFrontOriginAccessIdentities")
ListConflictingAliases = Action("ListConflictingAliases")
ListConnectionFunctions = Action("ListConnectionFunctions")
ListConnectionGroups = Action("ListConnectionGroups")
ListContinuousDeploymentPolicies = Action("ListContinuousDeploymentPolicies")
ListDistributionTenants = Action("ListDistributionTenants")
ListDistributionTenantsByCustomization = Action(
    "ListDistributionTenantsByCustomization"
)
ListDistributions = Action("ListDistributions")
ListDistributionsByAnycastIpListId = Action("ListDistributionsByAnycastIpListId")
ListDistributionsByCachePolicyId = Action("ListDistributionsByCachePolicyId")
ListDistributionsByConnectionFunction = Action("ListDistributionsByConnectionFunction")
ListDistributionsByConnectionMode = Action("ListDistributionsByConnectionMode")
ListDistributionsByKeyGroup = Action("ListDistributionsByKeyGroup")
ListDistributionsByLambdaFunction = Action("ListDistributionsByLambdaFunction")
ListDistributionsByOriginRequestPolicyId = Action(
    "ListDistributionsByOriginRequestPolicyId"
)
ListDistributionsByRealtimeLogConfig = Action("ListDistributionsByRealtimeLogConfig")
ListDistributionsByResponseHeadersPolicyId = Action(
    "ListDistributionsByResponseHeadersPolicyId"
)
ListDistributionsByTrustStore = Action("ListDistributionsByTrustStore")
ListDistributionsByVpcOriginId = Action("ListDistributionsByVpcOriginId")
ListDistributionsByWebACLId = Action("ListDistributionsByWebACLId")
ListDomainConflicts = Action("ListDomainConflicts")
ListFieldLevelEncryptionConfigs = Action("ListFieldLevelEncryptionConfigs")
ListFieldLevelEncryptionProfiles = Action("ListFieldLevelEncryptionProfiles")
ListFunctions = Action("ListFunctions")
ListInvalidations = Action("ListInvalidations")
ListInvalidationsForDistributionTenant = Action(
    "ListInvalidationsForDistributionTenant"
)
ListKeyGroups = Action("ListKeyGroups")
ListKeyValueStores = Action("ListKeyValueStores")
ListOriginAccessControls = Action("ListOriginAccessControls")
ListOriginRequestPolicies = Action("ListOriginRequestPolicies")
ListPublicKeys = Action("ListPublicKeys")
ListRateCards = Action("ListRateCards")
ListRealtimeLogConfigs = Action("ListRealtimeLogConfigs")
ListResponseHeadersPolicies = Action("ListResponseHeadersPolicies")
ListSavingsPlans = Action("ListSavingsPlans")
ListStreamingDistributions = Action("ListStreamingDistributions")
ListTagsForResource = Action("ListTagsForResource")
ListTrustStores = Action("ListTrustStores")
ListUsages = Action("ListUsages")
ListVpcOrigins = Action("ListVpcOrigins")
PublishConnectionFunction = Action("PublishConnectionFunction")
PublishFunction = Action("PublishFunction")
PutResourcePolicy = Action("PutResourcePolicy")
TagResource = Action("TagResource")
TestConnectionFunction = Action("TestConnectionFunction")
TestFunction = Action("TestFunction")
UntagResource = Action("UntagResource")
UpdateAnycastIpList = Action("UpdateAnycastIpList")
UpdateCachePolicy = Action("UpdateCachePolicy")
UpdateCloudFrontOriginAccessIdentity = Action("UpdateCloudFrontOriginAccessIdentity")
UpdateConnectionFunction = Action("UpdateConnectionFunction")
UpdateConnectionGroup = Action("UpdateConnectionGroup")
UpdateContinuousDeploymentPolicy = Action("UpdateContinuousDeploymentPolicy")
UpdateDistribution = Action("UpdateDistribution")
UpdateDistributionTenant = Action("UpdateDistributionTenant")
UpdateDistributionWithStagingConfig = Action("UpdateDistributionWithStagingConfig")
UpdateDomainAssociation = Action("UpdateDomainAssociation")
UpdateFieldLevelEncryptionConfig = Action("UpdateFieldLevelEncryptionConfig")
UpdateFieldLevelEncryptionProfile = Action("UpdateFieldLevelEncryptionProfile")
UpdateFunction = Action("UpdateFunction")
UpdateKeyGroup = Action("UpdateKeyGroup")
UpdateKeyValueStore = Action("UpdateKeyValueStore")
UpdateOriginAccessControl = Action("UpdateOriginAccessControl")
UpdateOriginRequestPolicy = Action("UpdateOriginRequestPolicy")
UpdatePublicKey = Action("UpdatePublicKey")
UpdateRealtimeLogConfig = Action("UpdateRealtimeLogConfig")
UpdateResponseHeadersPolicy = Action("UpdateResponseHeadersPolicy")
UpdateSavingsPlan = Action("UpdateSavingsPlan")
UpdateStreamingDistribution = Action("UpdateStreamingDistribution")
UpdateTrustStore = Action("UpdateTrustStore")
UpdateVpcOrigin = Action("UpdateVpcOrigin")
VerifyDnsConfiguration = Action("VerifyDnsConfiguration")
