# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon CloudWatch"
prefix = "cloudwatch"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AssumeAccessProfile = Action("AssumeAccessProfile")
BatchGetServiceLevelIndicatorReport = Action("BatchGetServiceLevelIndicatorReport")
BatchGetServiceLevelObjectiveBudgetReport = Action(
    "BatchGetServiceLevelObjectiveBudgetReport"
)
CallWithBearerToken = Action("CallWithBearerToken")
CreateAccessGrant = Action("CreateAccessGrant")
CreateAccessProfile = Action("CreateAccessProfile")
CreateAlert = Action("CreateAlert")
CreateDomain = Action("CreateDomain")
CreateDomainAccessGrantForOrganization = Action(
    "CreateDomainAccessGrantForOrganization"
)
CreateDomainForOrganization = Action("CreateDomainForOrganization")
CreateIngestionEndpoint = Action("CreateIngestionEndpoint")
CreateIntegration = Action("CreateIntegration")
CreateOmniDashboard = Action("CreateOmniDashboard")
CreateOmniThread = Action("CreateOmniThread")
CreateOneTimeDeepLinkCode = Action("CreateOneTimeDeepLinkCode")
CreateServiceLevelObjective = Action("CreateServiceLevelObjective")
CreateSpace = Action("CreateSpace")
CreateView = Action("CreateView")
DeleteAccessGrant = Action("DeleteAccessGrant")
DeleteAccessProfile = Action("DeleteAccessProfile")
DeleteAlarmMuteRule = Action("DeleteAlarmMuteRule")
DeleteAlarms = Action("DeleteAlarms")
DeleteAlert = Action("DeleteAlert")
DeleteAnomalyDetector = Action("DeleteAnomalyDetector")
DeleteDashboards = Action("DeleteDashboards")
DeleteDomain = Action("DeleteDomain")
DeleteDomainAccessGrantForOrganization = Action(
    "DeleteDomainAccessGrantForOrganization"
)
DeleteDomainForOrganization = Action("DeleteDomainForOrganization")
DeleteIngestionEndpoint = Action("DeleteIngestionEndpoint")
DeleteInsightRules = Action("DeleteInsightRules")
DeleteIntegration = Action("DeleteIntegration")
DeleteMetricStream = Action("DeleteMetricStream")
DeleteOmniDashboard = Action("DeleteOmniDashboard")
DeleteOmniThread = Action("DeleteOmniThread")
DeletePipelineRule = Action("DeletePipelineRule")
DeleteServiceLevelObjective = Action("DeleteServiceLevelObjective")
DeleteSpace = Action("DeleteSpace")
DeleteView = Action("DeleteView")
DescribeAlarmHistory = Action("DescribeAlarmHistory")
DescribeAlarms = Action("DescribeAlarms")
DescribeAlarmsForMetric = Action("DescribeAlarmsForMetric")
DescribeAnomalyDetectors = Action("DescribeAnomalyDetectors")
DescribeInsightRules = Action("DescribeInsightRules")
DisableAlarmActions = Action("DisableAlarmActions")
DisableInsightRules = Action("DisableInsightRules")
EnableAlarmActions = Action("EnableAlarmActions")
EnableInsightRules = Action("EnableInsightRules")
EnableTopologyDiscovery = Action("EnableTopologyDiscovery")
GenerateQuery = Action("GenerateQuery")
GenerateQueryResultsSummary = Action("GenerateQueryResultsSummary")
GetAccessGrant = Action("GetAccessGrant")
GetAccessProfile = Action("GetAccessProfile")
GetAgentGraph = Action("GetAgentGraph")
GetAlarmMuteRule = Action("GetAlarmMuteRule")
GetAlert = Action("GetAlert")
GetContextGraph = Action("GetContextGraph")
GetDashboard = Action("GetDashboard")
GetDataset = Action("GetDataset")
GetDomain = Action("GetDomain")
GetDomainAccessGrantForOrganization = Action("GetDomainAccessGrantForOrganization")
GetDomainForOrganization = Action("GetDomainForOrganization")
GetIngestionEndpoint = Action("GetIngestionEndpoint")
GetInsightRuleReport = Action("GetInsightRuleReport")
GetIntegration = Action("GetIntegration")
GetIntelligenceConfiguration = Action("GetIntelligenceConfiguration")
GetMetricData = Action("GetMetricData")
GetMetricStatistics = Action("GetMetricStatistics")
GetMetricStream = Action("GetMetricStream")
GetMetricWidgetImage = Action("GetMetricWidgetImage")
GetOTelEnrichment = Action("GetOTelEnrichment")
GetOmniDashboard = Action("GetOmniDashboard")
GetOmniThread = Action("GetOmniThread")
GetPreferences = Action("GetPreferences")
GetRecords = Action("GetRecords")
GetService = Action("GetService")
GetServiceData = Action("GetServiceData")
GetServiceLevelObjective = Action("GetServiceLevelObjective")
GetSpace = Action("GetSpace")
GetSpaceCredentials = Action("GetSpaceCredentials")
GetSpaceCredentialsForOrganization = Action("GetSpaceCredentialsForOrganization")
GetTelemetryQueryResults = Action("GetTelemetryQueryResults")
GetTopologyDiscoveryStatus = Action("GetTopologyDiscoveryStatus")
GetTopologyMap = Action("GetTopologyMap")
GetView = Action("GetView")
InvokeIntegration = Action("InvokeIntegration")
Link = Action("Link")
ListAccessGrants = Action("ListAccessGrants")
ListAccessProfiles = Action("ListAccessProfiles")
ListAlarmMuteRules = Action("ListAlarmMuteRules")
ListAlertContributors = Action("ListAlertContributors")
ListAlerts = Action("ListAlerts")
ListDashboards = Action("ListDashboards")
ListDomainAccessGrantsForOrganization = Action("ListDomainAccessGrantsForOrganization")
ListDomains = Action("ListDomains")
ListEntitiesForMetric = Action("ListEntitiesForMetric")
ListIngestionEndpoints = Action("ListIngestionEndpoints")
ListIntegrations = Action("ListIntegrations")
ListManagedInsightRules = Action("ListManagedInsightRules")
ListMetricStreams = Action("ListMetricStreams")
ListMetrics = Action("ListMetrics")
ListOmniDashboards = Action("ListOmniDashboards")
ListOmniThreads = Action("ListOmniThreads")
ListServiceLevelObjectives = Action("ListServiceLevelObjectives")
ListServices = Action("ListServices")
ListSpaceAccess = Action("ListSpaceAccess")
ListSpaces = Action("ListSpaces")
ListSpacesForOrganization = Action("ListSpacesForOrganization")
ListTagsForResource = Action("ListTagsForResource")
ListTelemetryFields = Action("ListTelemetryFields")
ListTelemetryQuerySessions = Action("ListTelemetryQuerySessions")
ListViews = Action("ListViews")
PutAlarmMuteRule = Action("PutAlarmMuteRule")
PutAnomalyDetector = Action("PutAnomalyDetector")
PutCompositeAlarm = Action("PutCompositeAlarm")
PutDashboard = Action("PutDashboard")
PutInsightRule = Action("PutInsightRule")
PutIntelligenceConfiguration = Action("PutIntelligenceConfiguration")
PutLogAlarm = Action("PutLogAlarm")
PutManagedInsightRules = Action("PutManagedInsightRules")
PutMetricAlarm = Action("PutMetricAlarm")
PutMetricData = Action("PutMetricData")
PutMetricStream = Action("PutMetricStream")
PutPipelineRule = Action("PutPipelineRule")
QueryTraces = Action("QueryTraces")
SearchPrincipals = Action("SearchPrincipals")
SetAlarmState = Action("SetAlarmState")
StartMetricStreams = Action("StartMetricStreams")
StartOTelEnrichment = Action("StartOTelEnrichment")
StartOmniThreadSession = Action("StartOmniThreadSession")
StartTelemetryQuery = Action("StartTelemetryQuery")
StartTelemetryQuerySession = Action("StartTelemetryQuerySession")
StopMetricStreams = Action("StopMetricStreams")
StopOTelEnrichment = Action("StopOTelEnrichment")
StopTelemetryQuery = Action("StopTelemetryQuery")
StopTelemetryQuerySession = Action("StopTelemetryQuerySession")
SubmitFeedback = Action("SubmitFeedback")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateAccessProfile = Action("UpdateAccessProfile")
UpdateAlert = Action("UpdateAlert")
UpdateDomain = Action("UpdateDomain")
UpdateDomainForOrganization = Action("UpdateDomainForOrganization")
UpdateIngestionEndpoint = Action("UpdateIngestionEndpoint")
UpdateIntegration = Action("UpdateIntegration")
UpdateOmniDashboard = Action("UpdateOmniDashboard")
UpdateOmniThread = Action("UpdateOmniThread")
UpdatePreferences = Action("UpdatePreferences")
UpdateServiceLevelObjective = Action("UpdateServiceLevelObjective")
UpdateSpace = Action("UpdateSpace")
UpdateView = Action("UpdateView")
