# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Cognito User Pools"
prefix = "cognito-idp"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AddCustomAttributes = Action("AddCustomAttributes")
AdminAddUserToGroup = Action("AdminAddUserToGroup")
AdminConfirmSignUp = Action("AdminConfirmSignUp")
AdminCreateUser = Action("AdminCreateUser")
AdminDeleteUser = Action("AdminDeleteUser")
AdminDeleteUserAttributes = Action("AdminDeleteUserAttributes")
AdminDisableProviderForUser = Action("AdminDisableProviderForUser")
AdminDisableUser = Action("AdminDisableUser")
AdminEnableUser = Action("AdminEnableUser")
AdminForgetDevice = Action("AdminForgetDevice")
AdminGetDevice = Action("AdminGetDevice")
AdminGetUser = Action("AdminGetUser")
AdminInitiateAuth = Action("AdminInitiateAuth")
AdminLinkProviderForUser = Action("AdminLinkProviderForUser")
AdminListDevices = Action("AdminListDevices")
AdminListGroupsForUser = Action("AdminListGroupsForUser")
AdminListUserAuthEvents = Action("AdminListUserAuthEvents")
AdminRemoveUserFromGroup = Action("AdminRemoveUserFromGroup")
AdminResetUserPassword = Action("AdminResetUserPassword")
AdminRespondToAuthChallenge = Action("AdminRespondToAuthChallenge")
AdminSetUserMFAPreference = Action("AdminSetUserMFAPreference")
AdminSetUserPassword = Action("AdminSetUserPassword")
AdminSetUserSettings = Action("AdminSetUserSettings")
AdminUpdateAuthEventFeedback = Action("AdminUpdateAuthEventFeedback")
AdminUpdateDeviceStatus = Action("AdminUpdateDeviceStatus")
AdminUpdateUserAttributes = Action("AdminUpdateUserAttributes")
AdminUserGlobalSignOut = Action("AdminUserGlobalSignOut")
AssociateSoftwareToken = Action("AssociateSoftwareToken")
AssociateWebACL = Action("AssociateWebACL")
ChangePassword = Action("ChangePassword")
ConfirmDevice = Action("ConfirmDevice")
ConfirmForgotPassword = Action("ConfirmForgotPassword")
ConfirmSignUp = Action("ConfirmSignUp")
CreateGroup = Action("CreateGroup")
CreateIdentityProvider = Action("CreateIdentityProvider")
CreateManagedLoginBranding = Action("CreateManagedLoginBranding")
CreateResourceServer = Action("CreateResourceServer")
CreateUserImportJob = Action("CreateUserImportJob")
CreateUserPool = Action("CreateUserPool")
CreateUserPoolClient = Action("CreateUserPoolClient")
CreateUserPoolDomain = Action("CreateUserPoolDomain")
DeleteGroup = Action("DeleteGroup")
DeleteIdentityProvider = Action("DeleteIdentityProvider")
DeleteManagedLoginBranding = Action("DeleteManagedLoginBranding")
DeleteResourceServer = Action("DeleteResourceServer")
DeleteUser = Action("DeleteUser")
DeleteUserAttributes = Action("DeleteUserAttributes")
DeleteUserPool = Action("DeleteUserPool")
DeleteUserPoolClient = Action("DeleteUserPoolClient")
DeleteUserPoolDomain = Action("DeleteUserPoolDomain")
DescribeIdentityProvider = Action("DescribeIdentityProvider")
DescribeManagedLoginBranding = Action("DescribeManagedLoginBranding")
DescribeManagedLoginBrandingByClient = Action("DescribeManagedLoginBrandingByClient")
DescribeResourceServer = Action("DescribeResourceServer")
DescribeRiskConfiguration = Action("DescribeRiskConfiguration")
DescribeUserImportJob = Action("DescribeUserImportJob")
DescribeUserPool = Action("DescribeUserPool")
DescribeUserPoolClient = Action("DescribeUserPoolClient")
DescribeUserPoolDomain = Action("DescribeUserPoolDomain")
DisassociateWebACL = Action("DisassociateWebACL")
ForgetDevice = Action("ForgetDevice")
ForgotPassword = Action("ForgotPassword")
GetCSVHeader = Action("GetCSVHeader")
GetDevice = Action("GetDevice")
GetGroup = Action("GetGroup")
GetIdentityProviderByIdentifier = Action("GetIdentityProviderByIdentifier")
GetLogDeliveryConfiguration = Action("GetLogDeliveryConfiguration")
GetSigningCertificate = Action("GetSigningCertificate")
GetUICustomization = Action("GetUICustomization")
GetUser = Action("GetUser")
GetUserAttributeVerificationCode = Action("GetUserAttributeVerificationCode")
GetUserPoolMfaConfig = Action("GetUserPoolMfaConfig")
GetWebACLForResource = Action("GetWebACLForResource")
GlobalSignOut = Action("GlobalSignOut")
InitiateAuth = Action("InitiateAuth")
ListDevices = Action("ListDevices")
ListGroups = Action("ListGroups")
ListIdentityProviders = Action("ListIdentityProviders")
ListResourceServers = Action("ListResourceServers")
ListResourcesForWebACL = Action("ListResourcesForWebACL")
ListTagsForResource = Action("ListTagsForResource")
ListUserImportJobs = Action("ListUserImportJobs")
ListUserPoolClients = Action("ListUserPoolClients")
ListUserPools = Action("ListUserPools")
ListUsers = Action("ListUsers")
ListUsersInGroup = Action("ListUsersInGroup")
ResendConfirmationCode = Action("ResendConfirmationCode")
RespondToAuthChallenge = Action("RespondToAuthChallenge")
RevokeToken = Action("RevokeToken")
SetLogDeliveryConfiguration = Action("SetLogDeliveryConfiguration")
SetRiskConfiguration = Action("SetRiskConfiguration")
SetUICustomization = Action("SetUICustomization")
SetUserMFAPreference = Action("SetUserMFAPreference")
SetUserPoolMfaConfig = Action("SetUserPoolMfaConfig")
SetUserSettings = Action("SetUserSettings")
SignUp = Action("SignUp")
StartUserImportJob = Action("StartUserImportJob")
StopUserImportJob = Action("StopUserImportJob")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateAuthEventFeedback = Action("UpdateAuthEventFeedback")
UpdateDeviceStatus = Action("UpdateDeviceStatus")
UpdateGroup = Action("UpdateGroup")
UpdateIdentityProvider = Action("UpdateIdentityProvider")
UpdateManagedLoginBranding = Action("UpdateManagedLoginBranding")
UpdateResourceServer = Action("UpdateResourceServer")
UpdateUserAttributes = Action("UpdateUserAttributes")
UpdateUserPool = Action("UpdateUserPool")
UpdateUserPoolClient = Action("UpdateUserPoolClient")
UpdateUserPoolDomain = Action("UpdateUserPoolDomain")
VerifySoftwareToken = Action("VerifySoftwareToken")
VerifyUserAttribute = Action("VerifyUserAttribute")
