# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon DataZone"
prefix = "datazone"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AcceptPredictions = Action("AcceptPredictions")
AcceptSubscriptionRequest = Action("AcceptSubscriptionRequest")
AddEntityOwner = Action("AddEntityOwner")
AddPolicyGrant = Action("AddPolicyGrant")
AssociateEnvironmentRole = Action("AssociateEnvironmentRole")
AssociateGovernedTerms = Action("AssociateGovernedTerms")
BatchDeleteLinkedTypes = Action("BatchDeleteLinkedTypes")
BatchGetAttributesMetadata = Action("BatchGetAttributesMetadata")
BatchGetCell = Action("BatchGetCell")
BatchGetCellRun = Action("BatchGetCellRun")
BatchPutAttributesMetadata = Action("BatchPutAttributesMetadata")
BatchPutLinkedTypes = Action("BatchPutLinkedTypes")
CancelMetadataGenerationRun = Action("CancelMetadataGenerationRun")
CancelSubscription = Action("CancelSubscription")
CreateAccountPool = Action("CreateAccountPool")
CreateAsset = Action("CreateAsset")
CreateAssetFilter = Action("CreateAssetFilter")
CreateAssetRevision = Action("CreateAssetRevision")
CreateAssetType = Action("CreateAssetType")
CreateCell = Action("CreateCell")
CreateCellRun = Action("CreateCellRun")
CreateConnection = Action("CreateConnection")
CreateDataProduct = Action("CreateDataProduct")
CreateDataProductRevision = Action("CreateDataProductRevision")
CreateDataSource = Action("CreateDataSource")
CreateDomain = Action("CreateDomain")
CreateDomainUnit = Action("CreateDomainUnit")
CreateEnvironment = Action("CreateEnvironment")
CreateEnvironmentAction = Action("CreateEnvironmentAction")
CreateEnvironmentBlueprint = Action("CreateEnvironmentBlueprint")
CreateEnvironmentProfile = Action("CreateEnvironmentProfile")
CreateFormType = Action("CreateFormType")
CreateGlossary = Action("CreateGlossary")
CreateGlossaryTerm = Action("CreateGlossaryTerm")
CreateGroupProfile = Action("CreateGroupProfile")
CreateListingChangeSet = Action("CreateListingChangeSet")
CreateNotebook = Action("CreateNotebook")
CreateProject = Action("CreateProject")
CreateProjectMembership = Action("CreateProjectMembership")
CreateProjectProfile = Action("CreateProjectProfile")
CreateRule = Action("CreateRule")
CreateSubscriptionGrant = Action("CreateSubscriptionGrant")
CreateSubscriptionRequest = Action("CreateSubscriptionRequest")
CreateSubscriptionTarget = Action("CreateSubscriptionTarget")
CreateUserProfile = Action("CreateUserProfile")
DeleteAccountPool = Action("DeleteAccountPool")
DeleteAsset = Action("DeleteAsset")
DeleteAssetFilter = Action("DeleteAssetFilter")
DeleteAssetType = Action("DeleteAssetType")
DeleteCell = Action("DeleteCell")
DeleteCellRun = Action("DeleteCellRun")
DeleteConnection = Action("DeleteConnection")
DeleteDataExportConfiguration = Action("DeleteDataExportConfiguration")
DeleteDataProduct = Action("DeleteDataProduct")
DeleteDataSource = Action("DeleteDataSource")
DeleteDomain = Action("DeleteDomain")
DeleteDomainSharingPolicy = Action("DeleteDomainSharingPolicy")
DeleteDomainUnit = Action("DeleteDomainUnit")
DeleteEnvironment = Action("DeleteEnvironment")
DeleteEnvironmentAction = Action("DeleteEnvironmentAction")
DeleteEnvironmentBlueprint = Action("DeleteEnvironmentBlueprint")
DeleteEnvironmentBlueprintConfiguration = Action(
    "DeleteEnvironmentBlueprintConfiguration"
)
DeleteEnvironmentProfile = Action("DeleteEnvironmentProfile")
DeleteFormType = Action("DeleteFormType")
DeleteGlossary = Action("DeleteGlossary")
DeleteGlossaryTerm = Action("DeleteGlossaryTerm")
DeleteListing = Action("DeleteListing")
DeleteNotebook = Action("DeleteNotebook")
DeleteProject = Action("DeleteProject")
DeleteProjectMembership = Action("DeleteProjectMembership")
DeleteProjectProfile = Action("DeleteProjectProfile")
DeleteRule = Action("DeleteRule")
DeleteSubscriptionGrant = Action("DeleteSubscriptionGrant")
DeleteSubscriptionRequest = Action("DeleteSubscriptionRequest")
DeleteSubscriptionTarget = Action("DeleteSubscriptionTarget")
DeleteTimeSeriesDataPoints = Action("DeleteTimeSeriesDataPoints")
DisassociateEnvironmentRole = Action("DisassociateEnvironmentRole")
DisassociateGovernedTerms = Action("DisassociateGovernedTerms")
GenerateCode = Action("GenerateCode")
GetAccountPool = Action("GetAccountPool")
GetAsset = Action("GetAsset")
GetAssetFilter = Action("GetAssetFilter")
GetAssetType = Action("GetAssetType")
GetCell = Action("GetCell")
GetCellRun = Action("GetCellRun")
GetCellRunResult = Action("GetCellRunResult")
GetConnection = Action("GetConnection")
GetConversation = Action("GetConversation")
GetDataExportConfiguration = Action("GetDataExportConfiguration")
GetDataProduct = Action("GetDataProduct")
GetDataSource = Action("GetDataSource")
GetDataSourceRun = Action("GetDataSourceRun")
GetDomain = Action("GetDomain")
GetDomainExecutionRoleCredentials = Action("GetDomainExecutionRoleCredentials")
GetDomainSharingPolicy = Action("GetDomainSharingPolicy")
GetDomainUnit = Action("GetDomainUnit")
GetEnvironment = Action("GetEnvironment")
GetEnvironmentAction = Action("GetEnvironmentAction")
GetEnvironmentActionLink = Action("GetEnvironmentActionLink")
GetEnvironmentBlueprint = Action("GetEnvironmentBlueprint")
GetEnvironmentBlueprintConfiguration = Action("GetEnvironmentBlueprintConfiguration")
GetEnvironmentCredentials = Action("GetEnvironmentCredentials")
GetEnvironmentProfile = Action("GetEnvironmentProfile")
GetFormType = Action("GetFormType")
GetGlossary = Action("GetGlossary")
GetGlossaryTerm = Action("GetGlossaryTerm")
GetGroupProfile = Action("GetGroupProfile")
GetIamPortalLoginUrl = Action("GetIamPortalLoginUrl")
GetJobRun = Action("GetJobRun")
GetLineageEvent = Action("GetLineageEvent")
GetLineageNode = Action("GetLineageNode")
GetListing = Action("GetListing")
GetMetadataGenerationRun = Action("GetMetadataGenerationRun")
GetNotebook = Action("GetNotebook")
GetNotebookCompute = Action("GetNotebookCompute")
GetProject = Action("GetProject")
GetProjectConfiguration = Action("GetProjectConfiguration")
GetProjectCredentials = Action("GetProjectCredentials")
GetProjectProfile = Action("GetProjectProfile")
GetRule = Action("GetRule")
GetSubscription = Action("GetSubscription")
GetSubscriptionEligibility = Action("GetSubscriptionEligibility")
GetSubscriptionGrant = Action("GetSubscriptionGrant")
GetSubscriptionRequestDetails = Action("GetSubscriptionRequestDetails")
GetSubscriptionTarget = Action("GetSubscriptionTarget")
GetTimeSeriesDataPoint = Action("GetTimeSeriesDataPoint")
GetUpdateEligibility = Action("GetUpdateEligibility")
GetUserProfile = Action("GetUserProfile")
ListAccountEnvironments = Action("ListAccountEnvironments")
ListAccountPools = Action("ListAccountPools")
ListAccountsInAccountPool = Action("ListAccountsInAccountPool")
ListAssetFilters = Action("ListAssetFilters")
ListAssetRevisions = Action("ListAssetRevisions")
ListCellRuns = Action("ListCellRuns")
ListConnections = Action("ListConnections")
ListConversations = Action("ListConversations")
ListDataProductRevisions = Action("ListDataProductRevisions")
ListDataSourceRunActivities = Action("ListDataSourceRunActivities")
ListDataSourceRuns = Action("ListDataSourceRuns")
ListDataSources = Action("ListDataSources")
ListDomainUnitsForParent = Action("ListDomainUnitsForParent")
ListDomains = Action("ListDomains")
ListEntityOwners = Action("ListEntityOwners")
ListEnvironmentActions = Action("ListEnvironmentActions")
ListEnvironmentBlueprintConfigurationSummaries = Action(
    "ListEnvironmentBlueprintConfigurationSummaries"
)
ListEnvironmentBlueprintConfigurations = Action(
    "ListEnvironmentBlueprintConfigurations"
)
ListEnvironmentBlueprints = Action("ListEnvironmentBlueprints")
ListEnvironmentProfiles = Action("ListEnvironmentProfiles")
ListEnvironments = Action("ListEnvironments")
ListGroupsForUser = Action("ListGroupsForUser")
ListJobRuns = Action("ListJobRuns")
ListLineageEvents = Action("ListLineageEvents")
ListLineageNodeHistory = Action("ListLineageNodeHistory")
ListLinkedTypes = Action("ListLinkedTypes")
ListMetadataGenerationRuns = Action("ListMetadataGenerationRuns")
ListNotebooks = Action("ListNotebooks")
ListNotifications = Action("ListNotifications")
ListPolicyGrants = Action("ListPolicyGrants")
ListProjectMemberships = Action("ListProjectMemberships")
ListProjectProfiles = Action("ListProjectProfiles")
ListProjects = Action("ListProjects")
ListRules = Action("ListRules")
ListSubscriptionGrants = Action("ListSubscriptionGrants")
ListSubscriptionRequests = Action("ListSubscriptionRequests")
ListSubscriptionTargets = Action("ListSubscriptionTargets")
ListSubscriptions = Action("ListSubscriptions")
ListTagsForResource = Action("ListTagsForResource")
ListTimeSeriesDataPoints = Action("ListTimeSeriesDataPoints")
ListUserProjects = Action("ListUserProjects")
ListWarehouseMetadata = Action("ListWarehouseMetadata")
PostLineageEvent = Action("PostLineageEvent")
PostTimeSeriesDataPoints = Action("PostTimeSeriesDataPoints")
ProvisionDomain = Action("ProvisionDomain")
PutCellRunResult = Action("PutCellRunResult")
PutDataExportConfiguration = Action("PutDataExportConfiguration")
PutDomainSharingPolicy = Action("PutDomainSharingPolicy")
PutEnvironmentBlueprintConfiguration = Action("PutEnvironmentBlueprintConfiguration")
QueryGraph = Action("QueryGraph")
RefreshToken = Action("RefreshToken")
RejectPredictions = Action("RejectPredictions")
RejectSubscriptionRequest = Action("RejectSubscriptionRequest")
RemoveEntityOwner = Action("RemoveEntityOwner")
RemovePolicyGrant = Action("RemovePolicyGrant")
RevokeSubscription = Action("RevokeSubscription")
Search = Action("Search")
SearchGroupProfiles = Action("SearchGroupProfiles")
SearchListings = Action("SearchListings")
SearchRules = Action("SearchRules")
SearchTypes = Action("SearchTypes")
SearchUserProfiles = Action("SearchUserProfiles")
SendMessage = Action("SendMessage")
SsoLogin = Action("SsoLogin")
SsoLogout = Action("SsoLogout")
StartAccountBootstrapAction = Action("StartAccountBootstrapAction")
StartConversation = Action("StartConversation")
StartDataSourceRun = Action("StartDataSourceRun")
StartMetadataGenerationRun = Action("StartMetadataGenerationRun")
StartNotebookCompute = Action("StartNotebookCompute")
StopMetadataGenerationRun = Action("StopMetadataGenerationRun")
StopNotebookCompute = Action("StopNotebookCompute")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateAccountPool = Action("UpdateAccountPool")
UpdateAssetFilter = Action("UpdateAssetFilter")
UpdateCell = Action("UpdateCell")
UpdateCellRun = Action("UpdateCellRun")
UpdateConnection = Action("UpdateConnection")
UpdateDataSource = Action("UpdateDataSource")
UpdateDataSourceRunActivities = Action("UpdateDataSourceRunActivities")
UpdateDomain = Action("UpdateDomain")
UpdateDomainUnit = Action("UpdateDomainUnit")
UpdateEnvironment = Action("UpdateEnvironment")
UpdateEnvironmentAction = Action("UpdateEnvironmentAction")
UpdateEnvironmentBlueprint = Action("UpdateEnvironmentBlueprint")
UpdateEnvironmentConfiguration = Action("UpdateEnvironmentConfiguration")
UpdateEnvironmentDeploymentStatus = Action("UpdateEnvironmentDeploymentStatus")
UpdateEnvironmentProfile = Action("UpdateEnvironmentProfile")
UpdateGlossary = Action("UpdateGlossary")
UpdateGlossaryTerm = Action("UpdateGlossaryTerm")
UpdateGroupProfile = Action("UpdateGroupProfile")
UpdateNotebook = Action("UpdateNotebook")
UpdateProject = Action("UpdateProject")
UpdateProjectProfile = Action("UpdateProjectProfile")
UpdateRule = Action("UpdateRule")
UpdateSubscriptionGrantStatus = Action("UpdateSubscriptionGrantStatus")
UpdateSubscriptionRequest = Action("UpdateSubscriptionRequest")
UpdateSubscriptionTarget = Action("UpdateSubscriptionTarget")
UpdateUserProfile = Action("UpdateUserProfile")
ValidatePassRole = Action("ValidatePassRole")
