# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS IoT SiteWise"
prefix = "iotsitewise"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AssociateAssets = Action("AssociateAssets")
AssociateGatewaySink = Action("AssociateGatewaySink")
AssociateGatewaySource = Action("AssociateGatewaySource")
AssociateTimeSeriesToAssetProperty = Action("AssociateTimeSeriesToAssetProperty")
AssociateViewEntities = Action("AssociateViewEntities")
BatchAssociateDataSegmentsToDataset = Action("BatchAssociateDataSegmentsToDataset")
BatchAssociateProjectAssets = Action("BatchAssociateProjectAssets")
BatchDeleteDatasetDataSegments = Action("BatchDeleteDatasetDataSegments")
BatchDisassociateDataSegmentsFromDataset = Action(
    "BatchDisassociateDataSegmentsFromDataset"
)
BatchDisassociateProjectAssets = Action("BatchDisassociateProjectAssets")
BatchGetAssetPropertyAggregates = Action("BatchGetAssetPropertyAggregates")
BatchGetAssetPropertyValue = Action("BatchGetAssetPropertyValue")
BatchGetAssetPropertyValueHistory = Action("BatchGetAssetPropertyValueHistory")
BatchPutAssetPropertyValue = Action("BatchPutAssetPropertyValue")
CancelEnrichmentJob = Action("CancelEnrichmentJob")
CancelPipelineExecution = Action("CancelPipelineExecution")
CancelQuery = Action("CancelQuery")
CreateAccessPolicy = Action("CreateAccessPolicy")
CreateApplication = Action("CreateApplication")
CreateAsset = Action("CreateAsset")
CreateAssetModel = Action("CreateAssetModel")
CreateAssetModelCompositeModel = Action("CreateAssetModelCompositeModel")
CreateAssetTemplate = Action("CreateAssetTemplate")
CreateBulkImportJob = Action("CreateBulkImportJob")
CreateComputationModel = Action("CreateComputationModel")
CreateDashboard = Action("CreateDashboard")
CreateDataset = Action("CreateDataset")
CreateDatasetExportJob = Action("CreateDatasetExportJob")
CreateEnrichmentJob = Action("CreateEnrichmentJob")
CreateGateway = Action("CreateGateway")
CreateGroup = Action("CreateGroup")
CreateMeasurementDataStore = Action("CreateMeasurementDataStore")
CreateMetricType = Action("CreateMetricType")
CreatePipeline = Action("CreatePipeline")
CreatePortal = Action("CreatePortal")
CreateProject = Action("CreateProject")
CreateTask = Action("CreateTask")
CreateView = Action("CreateView")
CreateWorkspace = Action("CreateWorkspace")
DeleteAccessPolicy = Action("DeleteAccessPolicy")
DeleteApplication = Action("DeleteApplication")
DeleteAsset = Action("DeleteAsset")
DeleteAssetModel = Action("DeleteAssetModel")
DeleteAssetModelCompositeModel = Action("DeleteAssetModelCompositeModel")
DeleteAssetModelInterfaceRelationship = Action("DeleteAssetModelInterfaceRelationship")
DeleteAssetTemplate = Action("DeleteAssetTemplate")
DeleteComputationModel = Action("DeleteComputationModel")
DeleteDashboard = Action("DeleteDashboard")
DeleteDataset = Action("DeleteDataset")
DeleteGateway = Action("DeleteGateway")
DeleteGroup = Action("DeleteGroup")
DeleteMeasurementDataStore = Action("DeleteMeasurementDataStore")
DeleteMetricType = Action("DeleteMetricType")
DeletePipeline = Action("DeletePipeline")
DeletePortal = Action("DeletePortal")
DeleteProject = Action("DeleteProject")
DeleteTask = Action("DeleteTask")
DeleteTimeSeries = Action("DeleteTimeSeries")
DeleteView = Action("DeleteView")
DeleteWorkspace = Action("DeleteWorkspace")
DeregisterViewEntities = Action("DeregisterViewEntities")
DescribeAccessPolicy = Action("DescribeAccessPolicy")
DescribeAction = Action("DescribeAction")
DescribeApplication = Action("DescribeApplication")
DescribeAsset = Action("DescribeAsset")
DescribeAssetCompositeModel = Action("DescribeAssetCompositeModel")
DescribeAssetModel = Action("DescribeAssetModel")
DescribeAssetModelCompositeModel = Action("DescribeAssetModelCompositeModel")
DescribeAssetModelInterfaceRelationship = Action(
    "DescribeAssetModelInterfaceRelationship"
)
DescribeAssetProperty = Action("DescribeAssetProperty")
DescribeAssetTemplates = Action("DescribeAssetTemplates")
DescribeAssets = Action("DescribeAssets")
DescribeBulkImportJob = Action("DescribeBulkImportJob")
DescribeComputationModel = Action("DescribeComputationModel")
DescribeComputationModelExecutionSummary = Action(
    "DescribeComputationModelExecutionSummary"
)
DescribeDashboard = Action("DescribeDashboard")
DescribeDataset = Action("DescribeDataset")
DescribeDatasetExportJob = Action("DescribeDatasetExportJob")
DescribeDefaultEncryptionConfiguration = Action(
    "DescribeDefaultEncryptionConfiguration"
)
DescribeEnrichmentJob = Action("DescribeEnrichmentJob")
DescribeExecution = Action("DescribeExecution")
DescribeGateway = Action("DescribeGateway")
DescribeGatewayCapabilityConfiguration = Action(
    "DescribeGatewayCapabilityConfiguration"
)
DescribeGateways = Action("DescribeGateways")
DescribeGroups = Action("DescribeGroups")
DescribeLoggingOptions = Action("DescribeLoggingOptions")
DescribeMeasurementDataStores = Action("DescribeMeasurementDataStores")
DescribeMetricTypes = Action("DescribeMetricTypes")
DescribePipeline = Action("DescribePipeline")
DescribePipelineExecution = Action("DescribePipelineExecution")
DescribePortal = Action("DescribePortal")
DescribeProject = Action("DescribeProject")
DescribeQuery = Action("DescribeQuery")
DescribeSearch = Action("DescribeSearch")
DescribeStorageConfiguration = Action("DescribeStorageConfiguration")
DescribeTask = Action("DescribeTask")
DescribeTimeSeries = Action("DescribeTimeSeries")
DescribeViews = Action("DescribeViews")
DescribeWorkspace = Action("DescribeWorkspace")
DisassociateAssets = Action("DisassociateAssets")
DisassociateGatewaySink = Action("DisassociateGatewaySink")
DisassociateGatewaySource = Action("DisassociateGatewaySource")
DisassociateTimeSeriesFromAssetProperty = Action(
    "DisassociateTimeSeriesFromAssetProperty"
)
DisassociateViewEntities = Action("DisassociateViewEntities")
EnableSiteWiseIntegration = Action("EnableSiteWiseIntegration")
ExecuteAction = Action("ExecuteAction")
ExecuteQuery = Action("ExecuteQuery")
GetAssetPropertyAggregates = Action("GetAssetPropertyAggregates")
GetAssetPropertyValue = Action("GetAssetPropertyValue")
GetAssetPropertyValueHistory = Action("GetAssetPropertyValueHistory")
GetCaptureData = Action("GetCaptureData")
GetInterpolatedAssetPropertyValues = Action("GetInterpolatedAssetPropertyValues")
GetMeasurementData = Action("GetMeasurementData")
GetMetricData = Action("GetMetricData")
GetQueryResults = Action("GetQueryResults")
GetSearchResults = Action("GetSearchResults")
InvokeAssistant = Action("InvokeAssistant")
ListAccessPolicies = Action("ListAccessPolicies")
ListActions = Action("ListActions")
ListApplications = Action("ListApplications")
ListAssetModelCompositeModels = Action("ListAssetModelCompositeModels")
ListAssetModelProperties = Action("ListAssetModelProperties")
ListAssetModels = Action("ListAssetModels")
ListAssetProperties = Action("ListAssetProperties")
ListAssetRelationships = Action("ListAssetRelationships")
ListAssetTemplates = Action("ListAssetTemplates")
ListAssets = Action("ListAssets")
ListAssociatedAssets = Action("ListAssociatedAssets")
ListBulkImportJobs = Action("ListBulkImportJobs")
ListCompositionRelationships = Action("ListCompositionRelationships")
ListComputationModelDataBindingUsages = Action("ListComputationModelDataBindingUsages")
ListComputationModelResolveToResources = Action(
    "ListComputationModelResolveToResources"
)
ListComputationModels = Action("ListComputationModels")
ListDashboards = Action("ListDashboards")
ListDatasetDataSegmentRelationships = Action("ListDatasetDataSegmentRelationships")
ListDatasetDataSegments = Action("ListDatasetDataSegments")
ListDatasetExportJobs = Action("ListDatasetExportJobs")
ListDatasets = Action("ListDatasets")
ListEnrichmentJobs = Action("ListEnrichmentJobs")
ListExecutions = Action("ListExecutions")
ListGateways = Action("ListGateways")
ListGroups = Action("ListGroups")
ListInterfaceRelationships = Action("ListInterfaceRelationships")
ListMeasurementDataStores = Action("ListMeasurementDataStores")
ListMeasurementDataStreams = Action("ListMeasurementDataStreams")
ListMetricTypes = Action("ListMetricTypes")
ListPipelineExecutions = Action("ListPipelineExecutions")
ListPipelines = Action("ListPipelines")
ListPortals = Action("ListPortals")
ListProjectAssets = Action("ListProjectAssets")
ListProjects = Action("ListProjects")
ListQueries = Action("ListQueries")
ListSearches = Action("ListSearches")
ListTagsForResource = Action("ListTagsForResource")
ListTasks = Action("ListTasks")
ListTimeSeries = Action("ListTimeSeries")
ListViewEntities = Action("ListViewEntities")
ListViews = Action("ListViews")
ListWorkspaces = Action("ListWorkspaces")
PutAssetModelInterfaceRelationship = Action("PutAssetModelInterfaceRelationship")
PutDefaultEncryptionConfiguration = Action("PutDefaultEncryptionConfiguration")
PutLoggingOptions = Action("PutLoggingOptions")
PutStorageConfiguration = Action("PutStorageConfiguration")
RegisterViewEntities = Action("RegisterViewEntities")
StartPipelineExecution = Action("StartPipelineExecution")
StartQuery = Action("StartQuery")
StartSearch = Action("StartSearch")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateAccessPolicy = Action("UpdateAccessPolicy")
UpdateAsset = Action("UpdateAsset")
UpdateAssetModel = Action("UpdateAssetModel")
UpdateAssetModelCompositeModel = Action("UpdateAssetModelCompositeModel")
UpdateAssetModelPropertyRouting = Action("UpdateAssetModelPropertyRouting")
UpdateAssetProperty = Action("UpdateAssetProperty")
UpdateAssetTemplate = Action("UpdateAssetTemplate")
UpdateComputationModel = Action("UpdateComputationModel")
UpdateDashboard = Action("UpdateDashboard")
UpdateDataset = Action("UpdateDataset")
UpdateGateway = Action("UpdateGateway")
UpdateGatewayCapabilityConfiguration = Action("UpdateGatewayCapabilityConfiguration")
UpdateGroup = Action("UpdateGroup")
UpdateMeasurementDataStore = Action("UpdateMeasurementDataStore")
UpdatePipeline = Action("UpdatePipeline")
UpdatePortal = Action("UpdatePortal")
UpdateProject = Action("UpdateProject")
UpdateTask = Action("UpdateTask")
UpdateView = Action("UpdateView")
UpdateWorkspace = Action("UpdateWorkspace")
