# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Connect Customer Profiles"
prefix = "profile"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AddProfileKey = Action("AddProfileKey")
BatchGetCalculatedAttributeForProfile = Action("BatchGetCalculatedAttributeForProfile")
BatchGetProfile = Action("BatchGetProfile")
CreateCalculatedAttributeDefinition = Action("CreateCalculatedAttributeDefinition")
CreateDomain = Action("CreateDomain")
CreateDomainLayout = Action("CreateDomainLayout")
CreateEventStream = Action("CreateEventStream")
CreateEventTrigger = Action("CreateEventTrigger")
CreateIntegrationWorkflow = Action("CreateIntegrationWorkflow")
CreateProfile = Action("CreateProfile")
CreateRecommender = Action("CreateRecommender")
CreateSegmentDefinition = Action("CreateSegmentDefinition")
CreateSegmentEstimate = Action("CreateSegmentEstimate")
CreateSegmentSnapshot = Action("CreateSegmentSnapshot")
CreateSnapshot = Action("CreateSnapshot")
CreateUploadJob = Action("CreateUploadJob")
DeleteCalculatedAttributeDefinition = Action("DeleteCalculatedAttributeDefinition")
DeleteDomain = Action("DeleteDomain")
DeleteDomainLayout = Action("DeleteDomainLayout")
DeleteDomainObjectType = Action("DeleteDomainObjectType")
DeleteEventStream = Action("DeleteEventStream")
DeleteEventTrigger = Action("DeleteEventTrigger")
DeleteIntegration = Action("DeleteIntegration")
DeleteProfile = Action("DeleteProfile")
DeleteProfileKey = Action("DeleteProfileKey")
DeleteProfileObject = Action("DeleteProfileObject")
DeleteProfileObjectType = Action("DeleteProfileObjectType")
DeleteRecommender = Action("DeleteRecommender")
DeleteSegmentDefinition = Action("DeleteSegmentDefinition")
DeleteWorkflow = Action("DeleteWorkflow")
DetectProfileObjectType = Action("DetectProfileObjectType")
GetAutoMergingPreview = Action("GetAutoMergingPreview")
GetCalculatedAttributeDefinition = Action("GetCalculatedAttributeDefinition")
GetCalculatedAttributeForProfile = Action("GetCalculatedAttributeForProfile")
GetDomain = Action("GetDomain")
GetDomainLayout = Action("GetDomainLayout")
GetDomainObjectType = Action("GetDomainObjectType")
GetEventStream = Action("GetEventStream")
GetEventTrigger = Action("GetEventTrigger")
GetIdentityResolutionJob = Action("GetIdentityResolutionJob")
GetIntegration = Action("GetIntegration")
GetMatches = Action("GetMatches")
GetObjectTypeAttributeStatistics = Action("GetObjectTypeAttributeStatistics")
GetProfileHistoryRecord = Action("GetProfileHistoryRecord")
GetProfileInsights = Action("GetProfileInsights")
GetProfileObjectType = Action("GetProfileObjectType")
GetProfileObjectTypeTemplate = Action("GetProfileObjectTypeTemplate")
GetProfileRecommendations = Action("GetProfileRecommendations")
GetRecommender = Action("GetRecommender")
GetSegmentDefinition = Action("GetSegmentDefinition")
GetSegmentEstimate = Action("GetSegmentEstimate")
GetSegmentMembership = Action("GetSegmentMembership")
GetSegmentSnapshot = Action("GetSegmentSnapshot")
GetSimilarProfiles = Action("GetSimilarProfiles")
GetSnapshot = Action("GetSnapshot")
GetUploadJob = Action("GetUploadJob")
GetUploadJobPath = Action("GetUploadJobPath")
GetWorkflow = Action("GetWorkflow")
GetWorkflowSteps = Action("GetWorkflowSteps")
ListAccountIntegrations = Action("ListAccountIntegrations")
ListCalculatedAttributeDefinitions = Action("ListCalculatedAttributeDefinitions")
ListCalculatedAttributesForProfile = Action("ListCalculatedAttributesForProfile")
ListDomainLayouts = Action("ListDomainLayouts")
ListDomainObjectTypes = Action("ListDomainObjectTypes")
ListDomainObjects = Action("ListDomainObjects")
ListDomains = Action("ListDomains")
ListEventStreams = Action("ListEventStreams")
ListEventTriggers = Action("ListEventTriggers")
ListIdentityResolutionJobs = Action("ListIdentityResolutionJobs")
ListIntegrations = Action("ListIntegrations")
ListObjectTypeAttributeValues = Action("ListObjectTypeAttributeValues")
ListObjectTypeAttributes = Action("ListObjectTypeAttributes")
ListProfileAttributeValues = Action("ListProfileAttributeValues")
ListProfileHistoryRecords = Action("ListProfileHistoryRecords")
ListProfileObjectTypeTemplates = Action("ListProfileObjectTypeTemplates")
ListProfileObjectTypes = Action("ListProfileObjectTypes")
ListProfileObjects = Action("ListProfileObjects")
ListRecommenderRecipes = Action("ListRecommenderRecipes")
ListRecommenders = Action("ListRecommenders")
ListRuleBasedMatches = Action("ListRuleBasedMatches")
ListSegmentDefinitions = Action("ListSegmentDefinitions")
ListTagsForResource = Action("ListTagsForResource")
ListUploadJobs = Action("ListUploadJobs")
ListWorkflows = Action("ListWorkflows")
MergeProfiles = Action("MergeProfiles")
PutDomainObjectType = Action("PutDomainObjectType")
PutIntegration = Action("PutIntegration")
PutProfileObject = Action("PutProfileObject")
PutProfileObjectType = Action("PutProfileObjectType")
SearchProfiles = Action("SearchProfiles")
StartRecommender = Action("StartRecommender")
StartUploadJob = Action("StartUploadJob")
StopRecommender = Action("StopRecommender")
StopUploadJob = Action("StopUploadJob")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateCalculatedAttributeDefinition = Action("UpdateCalculatedAttributeDefinition")
UpdateDomain = Action("UpdateDomain")
UpdateDomainLayout = Action("UpdateDomainLayout")
UpdateEventTrigger = Action("UpdateEventTrigger")
UpdateProfile = Action("UpdateProfile")
UpdateRecommender = Action("UpdateRecommender")
