# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.

from typing import Optional

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Security Agent"
prefix = "securityagent"


class Action(BaseAction):
    def __init__(self, action: Optional[str] = None) -> None:
        super().__init__(prefix, action)


class ARN(BaseARN):
    def __init__(self, resource: str = "", region: str = "", account: str = "") -> None:
        super().__init__(
            service=prefix, resource=resource, region=region, account=account
        )


AddArtifact = Action("AddArtifact")
AddControl = Action("AddControl")
BatchDeleteCodeReviews = Action("BatchDeleteCodeReviews")
BatchDeletePentests = Action("BatchDeletePentests")
BatchGetAgentInstances = Action("BatchGetAgentInstances")
BatchGetAgentSpaces = Action("BatchGetAgentSpaces")
BatchGetArtifactMetadata = Action("BatchGetArtifactMetadata")
BatchGetCodeReviewJobTasks = Action("BatchGetCodeReviewJobTasks")
BatchGetCodeReviewJobs = Action("BatchGetCodeReviewJobs")
BatchGetCodeReviews = Action("BatchGetCodeReviews")
BatchGetFindings = Action("BatchGetFindings")
BatchGetPentestJobContentMetadata = Action("BatchGetPentestJobContentMetadata")
BatchGetPentestJobTasks = Action("BatchGetPentestJobTasks")
BatchGetPentestJobs = Action("BatchGetPentestJobs")
BatchGetPentests = Action("BatchGetPentests")
BatchGetSecurityTestContentMetadata = Action("BatchGetSecurityTestContentMetadata")
BatchGetTargetDomains = Action("BatchGetTargetDomains")
BatchGetTasks = Action("BatchGetTasks")
CreateAgentInstance = Action("CreateAgentInstance")
CreateAgentSpace = Action("CreateAgentSpace")
CreateApplication = Action("CreateApplication")
CreateCodeReview = Action("CreateCodeReview")
CreateDesignReview = Action("CreateDesignReview")
CreateDocumentReview = Action("CreateDocumentReview")
CreateIntegration = Action("CreateIntegration")
CreateMembership = Action("CreateMembership")
CreateOneTimeLoginSession = Action("CreateOneTimeLoginSession")
CreatePentest = Action("CreatePentest")
CreateSecurityRequirement = Action("CreateSecurityRequirement")
CreateTargetDomain = Action("CreateTargetDomain")
DeleteAgentInstance = Action("DeleteAgentInstance")
DeleteAgentSpace = Action("DeleteAgentSpace")
DeleteApplication = Action("DeleteApplication")
DeleteArtifact = Action("DeleteArtifact")
DeleteControl = Action("DeleteControl")
DeleteDesignReview = Action("DeleteDesignReview")
DeleteDocumentReview = Action("DeleteDocumentReview")
DeleteIntegration = Action("DeleteIntegration")
DeleteMembership = Action("DeleteMembership")
DeleteSecurityRequirement = Action("DeleteSecurityRequirement")
DeleteTargetDomain = Action("DeleteTargetDomain")
DescribeFindings = Action("DescribeFindings")
GetApplication = Action("GetApplication")
GetArtifact = Action("GetArtifact")
GetCodeReviewTask = Action("GetCodeReviewTask")
GetControl = Action("GetControl")
GetDesignReview = Action("GetDesignReview")
GetDesignReviewArtifact = Action("GetDesignReviewArtifact")
GetDesignReviewFeedback = Action("GetDesignReviewFeedback")
GetDocReviewTask = Action("GetDocReviewTask")
GetDocumentReview = Action("GetDocumentReview")
GetDocumentReviewArtifact = Action("GetDocumentReviewArtifact")
GetIntegration = Action("GetIntegration")
GetLoginSessionCredentials = Action("GetLoginSessionCredentials")
GetSecurityRequirement = Action("GetSecurityRequirement")
HandleOneTimeLoginSession = Action("HandleOneTimeLoginSession")
InitiateProviderRegistration = Action("InitiateProviderRegistration")
ListAgentInstanceTasks = Action("ListAgentInstanceTasks")
ListAgentInstances = Action("ListAgentInstances")
ListAgentSpaces = Action("ListAgentSpaces")
ListApplications = Action("ListApplications")
ListArtifacts = Action("ListArtifacts")
ListCodeReviewJobTasks = Action("ListCodeReviewJobTasks")
ListCodeReviewJobsForCodeReview = Action("ListCodeReviewJobsForCodeReview")
ListCodeReviews = Action("ListCodeReviews")
ListControls = Action("ListControls")
ListDesignReviewComments = Action("ListDesignReviewComments")
ListDesignReviews = Action("ListDesignReviews")
ListDiscoveredEndpoints = Action("ListDiscoveredEndpoints")
ListDocumentReviewComments = Action("ListDocumentReviewComments")
ListDocumentReviews = Action("ListDocumentReviews")
ListFindings = Action("ListFindings")
ListIntegratedResources = Action("ListIntegratedResources")
ListIntegrations = Action("ListIntegrations")
ListMemberships = Action("ListMemberships")
ListPentestJobTasks = Action("ListPentestJobTasks")
ListPentestJobsForPentest = Action("ListPentestJobsForPentest")
ListPentests = Action("ListPentests")
ListResourcesFromIntegration = Action("ListResourcesFromIntegration")
ListSecurityRequirements = Action("ListSecurityRequirements")
ListTagsForResource = Action("ListTagsForResource")
ListTargetDomains = Action("ListTargetDomains")
ListTasks = Action("ListTasks")
PutDesignReviewFeedback = Action("PutDesignReviewFeedback")
StartCodeRemediation = Action("StartCodeRemediation")
StartCodeReviewJob = Action("StartCodeReviewJob")
StartPentestExecution = Action("StartPentestExecution")
StartPentestJob = Action("StartPentestJob")
StopCodeReviewJob = Action("StopCodeReviewJob")
StopPentestExecution = Action("StopPentestExecution")
StopPentestJob = Action("StopPentestJob")
TagResource = Action("TagResource")
ToggleManagedControl = Action("ToggleManagedControl")
ToggleManagedSecurityRequirement = Action("ToggleManagedSecurityRequirement")
UntagResource = Action("UntagResource")
UpdateAgentInstance = Action("UpdateAgentInstance")
UpdateAgentSpace = Action("UpdateAgentSpace")
UpdateApplication = Action("UpdateApplication")
UpdateCodeReview = Action("UpdateCodeReview")
UpdateControl = Action("UpdateControl")
UpdateFinding = Action("UpdateFinding")
UpdateIntegratedResources = Action("UpdateIntegratedResources")
UpdatePentest = Action("UpdatePentest")
UpdateSecurityRequirement = Action("UpdateSecurityRequirement")
UpdateTargetDomain = Action("UpdateTargetDomain")
VerifyTargetDomain = Action("VerifyTargetDomain")
