---
name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "twine>=3.4.1" "wheel>=0.36.2"
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Check basics before uploading the package
      run: |
        python -m tox -e package
    - name: Publish package on PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
