---
name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "build>=1.0.3" "twine>=4.0.2"
    - name: Build package
      run: |
        python -m build --sdist --wheel .
    - name: Check basics before uploading the package
      run: |
        python -m tox -e package
    - name: Publish package on PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
