---
name: Scrape Actions
on:
  schedule:
    - cron: '0 5 * * 1'  # every monday at 5 am

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r scrape/requirements.txt
          python -m pip install .
      - name: Scrape
        run: python ./scrape/scrape.py
      - name: Commit & push collected actions
        run: |
          git config user.name "GitHub Workflow"
          git config user.email cloudtools@users.noreply.github.com
          git add awacs/
          git commit -m "Action Update $(date "+%G-%V")" || true
          git push
